# Default configurations at https://github.com/helix-editor/helix/blob/master/languages.toml

# Markdown
[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
auto-format = true

# PHP
[language-server.phpactor]
command = "phpactor"
args = [ "language-server" ]
[[language]]
name = "php"
language-servers = [ "phpactor" ]

# Go
[[language]]
name = "go"
auto-format = true
formatter = { command = "gosimports" }

# JSON
[[language]]
name = "json"
# Until https://github.com/helix-editor/helix/issues/279 is resolved
# do not auto format, because it almost always indents wrong
auto-format = false
